package com.indieplaybook.app.data.source.local.dao

import androidx.room3.Dao
import androidx.room3.Delete
import androidx.room3.Query
import androidx.room3.Upsert
import com.indieplaybook.app.data.source.local.entity.ExampleEntity
import kotlinx.coroutines.flow.Flow

// Scaffolding DAO generated by make_local.sh as a template — safe to delete in a real app.
@Dao
interface ExampleDao {
    @Query("SELECT * FROM example WHERE id = :id")
    suspend fun getById(id: String): ExampleEntity?

    @Query("SELECT * FROM example WHERE id = :id")
    fun getByIdFlow(id: String): Flow<ExampleEntity?>

    @Query("SELECT * FROM example")
    fun getAllFlow(): Flow<List<ExampleEntity>>

    @Query("SELECT * FROM example")
    suspend fun getAll(): List<ExampleEntity>

    @Upsert
    suspend fun upsert(entity: ExampleEntity)

    @Query("DELETE FROM example WHERE id = :id")
    suspend fun deleteById(id: String)

    @Delete
    suspend fun delete(entity: ExampleEntity)

    @Query("DELETE FROM example")
    suspend fun deleteAll()
}
