package com.indieplaybook.app.domain.model

data class AppStory(
    val id: String,
    val name: String,
    val oneLiner: String,
    val techStack: String,
    val originStory: String,
    val growthPlaybook: String,
    val iconUrl: String,
    val isBookmarked: Boolean,
    val downloads: String? = null,
    val revenue: String? = null,
    val publisher: String? = null,
    val releaseDate: String? = null,
    val category: String? = null,
    val googlePlayUrl: String? = null,
    val appStoreUrl: String? = null,
    val googlePlayReviews: String? = null,
    val googlePlayRating: Double? = null,
    val googlePlayAbout: String? = null,
    val appStoreRating: Double? = null,
    val appStoreReviews: Int? = null,
    val appStoreSize: String? = null,
    val appStoreChartRank: Int? = null,
    val appStoreChartCategory: String? = null,
    val appStoreAbout: String? = null,
    val appStoreAgeRating: String? = null,
    val appStorePrivacyPolicy: String? = null,
    val googlePlayPrivacyPolicy: String? = null,
    val appWebsiteUrl: String? = null
)
